// This is auto-generated by scripts/downloadReleases.js
define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.supportedReleases = [
        "2.4.1",
        "2.7.2",
        "2.8.1",
        "3.0.1",
        "3.1.6",
        "3.3.3",
        "3.5.1",
        "3.6.3",
        "3.7.5",
        "3.8.2",
        "3.8.3"
    ];
});
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVsZWFzZXMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi9zYW5kYm94L3NyYy9yZWxlYXNlcy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSx3REFBd0Q7Ozs7SUFFM0MsUUFBQSxpQkFBaUIsR0FBRztRQUMvQixPQUFPO1FBQ1AsT0FBTztRQUNQLE9BQU87UUFDUCxPQUFPO1FBQ1AsT0FBTztRQUNQLE9BQU87UUFDUCxPQUFPO1FBQ1AsT0FBTztRQUNQLE9BQU87UUFDUCxPQUFPO1FBQ1AsT0FBTztLQUNDLENBQUMiLCJzb3VyY2VzQ29udGVudCI6WyIvLyBUaGlzIGlzIGF1dG8tZ2VuZXJhdGVkIGJ5IHNjcmlwdHMvZG93bmxvYWRSZWxlYXNlcy5qc1xuXG5leHBvcnQgY29uc3Qgc3VwcG9ydGVkUmVsZWFzZXMgPSBbXG4gIFwiMi40LjFcIixcbiAgXCIyLjcuMlwiLFxuICBcIjIuOC4xXCIsXG4gIFwiMy4wLjFcIixcbiAgXCIzLjEuNlwiLFxuICBcIjMuMy4zXCIsXG4gIFwiMy41LjFcIixcbiAgXCIzLjYuM1wiLFxuICBcIjMuNy41XCIsXG4gIFwiMy44LjJcIixcbiAgXCIzLjguM1wiXG5dIGFzIGNvbnN0O1xuXG5leHBvcnQgdHlwZSBSZWxlYXNlVmVyc2lvbnMgPVxuICB8IFwiMi40LjFcIlxuICB8IFwiMi43LjJcIlxuICB8IFwiMi44LjFcIlxuICB8IFwiMy4wLjFcIlxuICB8IFwiMy4xLjZcIlxuICB8IFwiMy4zLjNcIlxuICB8IFwiMy41LjFcIlxuICB8IFwiMy42LjNcIlxuICB8IFwiMy43LjVcIlxuICB8IFwiMy44LjJcIlxuICB8IFwiMy44LjNcIjtcbiJdfQ==